version: "3.8"
services:
  client:
    build: ./client
    image: finance-client
    container_name: portal-client
    ports:
      - "8080:80"
    volumes:
      - ./client:/app

  server:
    build: ./server
    image: finance-server
    container_name: portal-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app