version: "3.8"

services:
  client:
    build: ./client
    image: finance-client
    container_name: portal-client
    ports:
      - "3000:30"

  server:
    build: ./server
    image: finance-server
    container_name: portal-server
    ports:
      - "5000:5000"
    env_file: 
    - ./server/.env
    volumes:
      - ./server:/app
